server {
    listen 80;
    root /usr/share/nginx/html; #cartella contenente i file statici generati da Vite
    index index.html;

    # SPA fallback: tutte le route passano da index.html
    #blocco di gestione della richiesta
     # Strategia di fallback in tre passi:
     # 1. Cerca il file esatto richiesto ($uri)
     # 2. Cerca una cartella con quel nome ($uri/)
     # 3. Se non trova nulla, serve sempre index.html
     # Il punto 3 è il SPA fallback — permette a React Router di funzionare
    location / {
        try_files $uri $uri/ /index.html;
    }

    # REVERSE PROXY: Intercetta le chiamate /api/ e le gira al Gateway
    location /api/ {
        proxy_pass http://gateway:8080/api/gateway/;
        proxy_set_header Host $host; #passa l'hostname originale della richiesta
        proxy_set_header X-Real-IP $remote_addr;#passa l'ip reale del client
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;#lista completa degli ip attraversati dalla richiesta
        proxy_set_header X-Forwarded-Proto $scheme;#indica se la richiesta era HTTP o HTTPS
    }
}
